### ISSUE TITLE
Add a footer to the posts saying that the post was made with the drafter

### ISSUE THREAD

**Issue by derwasp** [philip-gai/announcement-drafter#58]
**Is your feature request related to a problem? Please describe.**
More people will know about the tool if the posts reference it.

**Describe the solution you'd like**
Add a footer to the posts saying that the post was made with the drafter

**Comment by philip-gai** [comment]
Footer format:

> Published with ❤️  by [Announcement Drafter](https://github.com/apps/announcement-drafter)
