### ISSUE TITLE
[Feature Request] Footer improvement: include the link to the original PR

### ISSUE THREAD

**Issue by derwasp** [philip-gai/announcement-drafter#78]
**Is your feature request related to a problem? Please describe.**
As of https://github.com/philip-gai/announcement-drafter/issues/58 posts already have a footer. It would be nice if there would be a link to the original PR so that one can navigate there.

**Describe the solution you'd like**
A link to the PR alongside a not that the post is made by the drafter.

**Comment by philip-gai** [comment]
This is a great idea and has crossed my mind. Not hard to implement either. The main issue I have is I'm not sure people would want links to private repos that the audience might not have access to or be aware of? What do you think?

**Comment by derwasp** [comment]
Yeah, this makes sense. Maybe we can make this configurable in the comment block?

**Comment by philip-gai** [comment]
Yeah. I think what I can do is:

1. If it's a public repo, just always include the link back to the PR
2. If it's a private repo, check the comment block options and see if the user wants it enabled

I have a feeling users won't read the options and know to opt-in, but still think it's worth adding for power users like us 😄

**Comment by philip-gai** [comment]
Closing because I implemented pr linking for public repos by default. Created a separate issue for supporting a markdown header option in https://github.com/philip-gai/announcement-drafter/issues/95
